version: '2'
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
    - ${volumeConfig}:/mosquitto/config/mosquitto.conf:rw
    - ${volumeData}:/mosquitto/data:rw
    - ${volumeLog}:/mosquitto/log:rw
    ports:
    - '9001:9001'
    - '1883:1883'
    environment:
    - TZ=Europe/Lisbon
    network_mode: host