version: '2'
services:
  mosquitto:
    image: toke/mosquitto
    restart: unless-stopped
    volumes:
    - ${volumeConfig}:/mqtt/config:rw
    - ${volumeData}:/mqtt/data:rw
    - ${volumeLog}:/mqtt/log:rw
    ports:
    - '9001:9001'
    - '1883:1883'
    environment:
    - TZ=Europe/Lisbon
    network_mode: host