.catalog:
  name: "Mosquitto"
  version: "v1"
  description: "Mosquitto"
  uuid: mosquitto-1
  questions:
    #VOLUMES
    - variable: volumeConfig
      description: ""
      label: "Path for Config"
      type: "string"
      required: true
      default: "/host/dockers/Mosquitto/config"
    - variable: volumeData
      description: ""
      label: "Path for Data"
      type: "string"
      required: true
      default: "/host/dockers/Mosquitto/data"
    - variable: volumeLog
      description: ""
      label: "Path for Log"
      type: "string"
      required: true
      default: "/host/dockers/Mosquitto/log"

mosquitto:
  scale: 1
  start_on_create: true