version: '2'
services:
  homeassistant:
    image: homeassistant/home-assistant
    restart: unless-stopped
    volumes:
    - ${volumeConfig}:/config:rw
    environment:
    - TZ=Europe/Lisbon
    network_mode: host