version: '2'
services:
  csgo:
    image: cm2network/csgo:sourcemod
    restart: unless-stopped
    volumes:
    - ${VOLUME}:/home/steam/csgo-dedicated:rw
    ports:
    - ${PORT}:27015
    - ${PORTTV}:27020
    environment:
    - SRCDS_TOKEN=${TOKEN}
    - SRCDS_RCONPW=${RCONPW}
    - SRCDS_PW=${PW}
    - SRCDS_FPSMAX=${FPSMAX}
    - SRCDS_TICKRATE=${TICKRATE}
    - SRCDS_MAXPLAYERS=${MAXPLAYERS}
    - SRCDS_STARTMAP=${STARTMAP}
    - SRCDS_REGION=${REGION}
    - SRCDS_MAPGROUP=${MAPGROUP}
    network_mode: host