version: '2'
services:
  csgo:
    image: kmallea/csgo
    restart: unless-stopped
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
    - ${VOLUME}:/home/steam/csgo:rw
    ports:
    - ${PORT}:27015
    - ${PORTTV}:27020
    environment:
    - SERVER_HOSTNAME=${HOSTNAME}
    - SERVER_PASSWORD=${PW}
    - RCON_PASSWORD=${RCONPW}
    - STEAM_ACCOUNT=${TOKEN}
    - AUTHKEY=${AUTHKEY}
    - SOURCEMOD_ADMINS=${SOURCEMOD_ADMINS}
    - IP=0.0.0.0
    - PORT=27015
    - TV_PORT=27020
    - TICKRATE=${TICKRATE}
    - FPS_MAX=${FPSMAX}
    - GAME_TYPE=${GAME_TYPE}
    - GAME_MODE=${GAME_MODE}
    - MAP=${STARTMAP}
    - MAPGROUP=${MAPGROUP}
    - MAXPLAYERS=${MAXPLAYERS}
    - TV_ENABLE=${TV_ENABLE}
    - LAN=${LAN}
    - RETAKES=${RETAKES}
    - INSTALL_PLUGINS=${INSTALL_PLUGINS}
    