.catalog:
  name: "Plex Media Server"
  version: "v1"
  description: "Plex Media Server"
  uuid: pms-1
  questions:
    #VOLUMES
    - variable: volumeConfig
      description: "The path where you wish Plex Media Server to store its configuration data. This database can grow to be quite large depending on the size of your media collection. This is usually a few GB but for large libraries or libraries where index files are generated, this can easily hit the 100s of GBs. If you have an existing database directory see the section below on the directory setup. Note: the underlying filesystem needs to support file locking. This is known to not be default enabled on remote filesystems like NFS, SMB, and many many others. The 9PFS filesystem used by FreeNAS Corral is known to work but the vast majority will result in database corruption. Use a network share at your own risk."
      label: "Path for Config"
      type: "string"
      required: true
      default: "/host/data/dockers/PlexMediaServer/config"

    - variable: volumeTranscode
      description: "The path where you would like Plex Media Server to store its transcoder temp files. If not provided, the storage space within the container will be used. Expect sizes in the 10s of GB."
      label: "Path for Transcode"
      type: "string"
      required: true
      default: "/host/data/dockers/PlexMediaServer/transcode"

    - variable: volumeData
      description: "This is provided as examples for providing media into the container. The exact structure of how the media is organized and presented inside the container is a matter of user preference. You can use as many or as few of these parameters as required to provide your media to the container."
      label: "Path for Data"
      type: "string"
      required: true
      default: "/host/data/dockers/PlexMediaServer/data"

    - variable: volumeMedia
      description: "Adicional media path"
      label: "Path for Media"
      type: "string"
      required: true
      default: "/host/data/media"

    #SHARED
    - variable: envTimezone
      description: "Set the timezone inside the container. For example: Europe/London. The complete list can be found here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"
      label: "TZ"
      type: "string"
      required: true
      default: "Europe/London"

    - variable: envPGID
      description: "The group id of the plex group created inside the container."
      label: "PLEX_GID"
      type: "int"
      required: true
      default: 1001

    - variable: envPUID
      description: "The user id of the plex user created inside the container."
      label: "PLEX_UID"
      type: "int"
      required: true
      default: 1001

    - variable: envPlexClaim
      description: "The claim token for the server to obtain a real server token. If not provided, server is will not be automatically logged in. If server is already logged in, this parameter is ignored. You can obtain a claim token to login your server to your plex account by visiting https://www.plex.tv/claim"
      label: "PLEX_CLAIM"
      type: "string"
      required: false
      default: ""

    - variable: envAllowedNetworks
      description: "IP/netmask entries which allow access to the server without requiring authorization. We recommend you set this only if you do not sign in your server. For example 192.168.1.0/24,172.16.0.0/16 will allow access to the entire 192.168.1.x range and the 172.16.x.x range. Note: If you are using Bridge networking, then localhost will appear to plex as coming from the docker networking gateway which is often 172.16.0.1."
      label: "ALLOWED_NETWORKS"
      type: "string"
      required: false
      default: "192.168.1.0/255.255.255.0"

    #NETWORKING
    - variable: networkMode
      description: "The type of networking you wish to use"
      label: "Network Mode"
      type: "enum"
      options:
        - host
        - bridge
        #- macvlan
      required: true
      default: "host"

    - variable: hostname
      description: "Sets the hostname inside the docker container. For example -h PlexServer will set the servername to PlexServer. Not needed in Host Networking."
      label: "Hostname"
      type: "string"
      required: false
      default: ""

    #bridge
    - variable: envAdvertiseIp
      description: "This variable defines the additional IPs on which the server may be be found. For example: http://10.1.1.23:32400. This adds to the list where the server advertises that it can be found. This is only needed in Bridge Networking."
      label: "ADVERTISE_IP"
      type: "string"
      required: false
      default: ""

    #macvlan
    #- variable: ipv4Address
    #  description: "Only for type macvlan network"
    #  label: "IPV4 Address"
    #  type: "string"
    #  required: false
    #  default: ""
      
plex-media-server:
  scale: 1
  start_on_create: true