.catalog:
  name: "Plex Media Server"
  version: "v1"
  description: "Plex Media Server"
  uuid: pms-1
  questions:
    #VOLUMES
    - variable: volumeConfig
      description: "The path where you wish Plex Media Server to store its configuration data. This database can grow to be quite large depending on the size of your media collection. This is usually a few GB but for large libraries or libraries where index files are generated, this can easily hit the 100s of GBs. If you have an existing database directory see the section below on the directory setup. Note: the underlying filesystem needs to support file locking. This is known to not be default enabled on remote filesystems like NFS, SMB, and many many others. The 9PFS filesystem used by FreeNAS Corral is known to work but the vast majority will result in database corruption. Use a network share at your own risk."
      label: "Volume Config"
      type: "string"
      required: true
      default: "/host/data/dockers/PlexMediaServer/config"
    - variable: volumeData
      description: "Volume for /data"
      label: "Volume Data"
      type: "string"
      required: true
      default: "/host/data/dockers/PlexMediaServer/data"
    - variable: volumeMedia
      description: "Volume for /media"
      label: "Volume Media"
      type: "string"
      required: true
      default: "/host/data/media"
    - variable: volumeTranscode
      description: "Volume for /transcode"
      label: "Volume Transcode"
      type: "string"
      required: true
      default: "/host/data/dockers/PlexMediaServer/transcode"
    #NETWORKING
    - variable: networkMode
      description: "Network Mode"
      label: "Network Mode"
      type: "enum"
      options:
        - host
        - bridge
        - macvlan
      required: true
      default: "host"

    - variable: envAdvertiseIp
      description: "Env Var ADVERTISE_IP"
      label: "ADVERTISE_IP"
      type: "string"
      required: true
      default: "http://192.168.1.50:32400/"
    - variable: envAllowedNetworks
      description: "Env Var ALLOWED_NETWORKS"
      label: "ALLOWED_NETWORKS"
      type: "string"
      required: true
      default: "192.168.1.0/255.255.255.0"
    - variable: envTimezone
      description: "Env Var TZ"
      label: "TZ"
      type: "string"
      required: true
      default: "Europe/London"
    - variable: envPGID
      description: "Env Var PGID"
      label: "PGID"
      type: "int"
      required: true
      default: "1001"
    - variable: envPUID
      description: "Env Var PUID"
      label: "PUID"
      type: "int"
      required: true
      default: "1001"

plex-media-server:
  scale: 1
  start_on_create: true