version: '2'
services:
  alpine-so:
    image: lsiobase/alpine
    restart: unless-stopped
    networks:
      external:
        ipv4_address: 192.168.1.200
networks:
  external:
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
        - gateway: 192.168.1.254