version: '2'
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${volumeConfig}:/app/config/production.json
      - ${volumeData}:/data
      - ${volumeLetsencrypt}:/etc/letsencrypt
    ports:
      - ${portHttp}:80
      - ${portAdmin}:81
      - ${portHttps}:443
  db:
    image: 'mariadb'
    restart: unless-stopped
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: '${mySqlRootPassword}'
      MYSQL_DATABASE: '${mySqlDatabase}'
      MYSQL_USER: '${mySqlUser}'
      MYSQL_PASSWORD: '${mySqlPassword}'
    volumes:
      - ${volumeMySql}:/var/lib/mysql
    command: '--innodb-flush-method=fsync'