version: '2'
services:
  rancher-active-proxy:
    image: adi90x/rancher-active-proxy
    environment:
      DEFAULT_HOST: ${DEFAULT_HOST}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      CRON: ${CRON}
      DEBUG: ${DEBUG}
      DEFAULT_PORT: ${DEFAULT_PORT}
    stdin_open: true
    volumes:
      - ${PATH}/htpasswd:/etc/nginx/htpasswd
      - ${PATH}/vhost.d:/etc/nginx/vhost.d
      - ${PATH}/letsencrypt:/etc/letsencrypt
      - ${PATH}/conf.d:/etc/nginx/conf.d
      - ${PATH}/certs:/etc/nginx/certs
      - ${PATH}/log:/var/log/nginx
    tty: true
    ports:
      - ${DEFAULT_PORT}:80/tcp
      - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always
  duartebrito:
    image: nginx
    ports:
      - "0.0.0.0:9080:80"
    volumes:
      - ${vConfd}:/etc/nginx/conf.d:rw
      - ${vHtml}:/usr/share/nginx/html:rw
      - ${vCerts}:/etc/nginx/certs:rw
    network_mode: host
    labels:
      rap.host: duartebrito.com=>http:9080,www.duartebrito.com=>http:9080
      rap.le_host: duartebrito.com,www.duartebrito.com
      rap.le_email: sytertzp@gmail.com
      rap.le_bypass: true