version: '2'
services:
  transmission-client:
    image: linuxserver/transmission
    restart: unless-stopped
    volumes:
    - ${volumeConfig}:/config:rw
    - ${volumeDownloads}:/downloads:rw
    - ${volumeMedia}:/shared:rw
    - ${volumeWatch}:/watch:rw
    network_mode: host
    environment:
      PGID: ${envPGID}
      PUID: ${envPUID}
      TZ: ${envTimezone}