version: '2'
services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
    - ${PORT}:25565
    volumes:
    - ${volumeData}:/data:rw
    - ${volumeModpacks}:/modpacks:rw
    environment:
      EULA: "TRUE"
      TZ: Europe/London
      VERSION: ${VERSION}
      TYPE: ${TYPE}
      SERVER_NAME: ${SERVER_NAME}
      DIFFICULTY: ${DIFFICULTY}
      OPS: ${OPS}
      #MEMORY: ${MEMORY}
      CF_SERVER_MOD: ${CF_SERVER_MOD}
      USE_MODPACK_START_SCRIPT: ${USE_MODPACK_START_SCRIPT}
      FTB_LEGACYJAVAFIXER: ${FTB_LEGACYJAVAFIXER}
      #ENABLE_RCON: "true"
      #RCON_PASSWORD: ${RCON_PASSWORD}
      #RCON_PORT: 28016
      #REPLACE_ENV_VARIABLES: "TRUE"
      #ENV_VARIABLE_PREFIX: "CFG_"
      #INIT_MEMORY: ${INIT_MEMORY}
      #MAX_MEMORY: ${MAX_MEMORY}
      #ENABLE_AUTOPAUSE: "TRUE"
      #OVERRIDE_SERVER_PROPERTIES: "TRUE"
      #MAX_TICK_TIME: "-1"
    network_mode: host