version: '2'
services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
    - ${PORT}:25565
    volumes:
    - ${volumeData}:/data:rw
    environment:
      EULA: "TRUE"
      TZ: Europe/London
      TYPE: TUINITY
      SERVER_NAME: ${SERVER_NAME}
      DIFFICULTY: ${DIFFICULTY}
      OPS: ${OPS}
      #ENABLE_RCON: "true"
      #RCON_PASSWORD: ${RCON_PASSWORD}
      #RCON_PORT: 28016
      #REPLACE_ENV_VARIABLES: "TRUE"
      #ENV_VARIABLE_PREFIX: "CFG_"
      #MEMORY: ${MEMORY}
      #INIT_MEMORY: ${INIT_MEMORY}
      #MAX_MEMORY: ${MAX_MEMORY}
      #ENABLE_AUTOPAUSE: "TRUE"
      #OVERRIDE_SERVER_PROPERTIES: "TRUE"
      #MAX_TICK_TIME: "-1"
    network_mode: host