version: '2'
services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
    - "25565:25565"
    volumes:
    - ${volumeData}:/data:rw
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CFG_"
      SERVER_NAME: ${SERVER_NAME}
      DIFFICULTY: ${DIFFICULTY}
      OPS: ${OPS}
    network_mode: host
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - ${volumeRcon}:/opt/rcon-web-admin/db:rw