.catalog:
  name: "Minecraft"
  version: "v1"
  description: "Minecraft"
  uuid: minecraft-1
  questions:
    #VOLUMES
    - variable: PORT
      description: ""
      label: "port"
      type: "string"
      required: true
      default: "25565"
    - variable: volumeData
      description: ""
      label: "Path for Config"
      type: "string"
      required: true
      default: "/host/dockers/Minecraft/data"
    # - variable: RCON_PASSWORD
    #   description: ""
    #   label: "RCON_PASSWORD"
    #   type: "string"
    #   required: true
    #   default: "TOCHANGE"
    - variable: SERVER_NAME
      description: ""
      label: "SERVER_NAME"
      type: "string"
      required: true
      default: "LadyStarPT World"
    - variable: DIFFICULTY
      description: "Valid values are: peaceful, easy, normal, and hard, and an error message will be output in the logs if it's not one of these values."
      label: "DIFFICULTY"
      type: "string"
      required: true
      default: "peaceful"
    - variable: OPS
      description: ""
      label: "OPS"
      type: "string"
      required: true
      default: "SyTeRPT,mamocas"
    # - variable: MEMORY
    #   description: "The values of all three are passed directly to the JVM and support format/units as <size>[g|G|m|M|k|K]."
    #   label: "MEMORY"
    #   type: "string"
    #   required: true
    #   default: "3G"
    # - variable: INIT_MEMORY
    #   description: "The values of all three are passed directly to the JVM and support format/units as <size>[g|G|m|M|k|K]."
    #   label: "INIT_MEMORY"
    #   type: "string"
    #   required: true
    #   default: "1G"
    # - variable: MAX_MEMORY
    #   description: "The values of all three are passed directly to the JVM and support format/units as <size>[g|G|m|M|k|K]."
    #   label: "MAX_MEMORY"
    #   type: "string"
    #   required: true
    #   default: "2.5G"

minecraft:
  scale: 1
  start_on_create: true