.catalog:
  name: "Minecraft"
  version: "v1"
  description: "Minecraft"
  uuid: minecraft-1
  questions:
    #VOLUMES
    - variable: volumeData
      description: ""
      label: "Path for Config"
      type: "string"
      required: true
      default: "/host/dockers/Minecraft/data"
    - variable: volumeData
      description: ""
      label: "Path for Config"
      type: "string"
      required: true
      default: "/host/dockers/Minecraft/rcon"
    - variable: RCON_PASSWORD
      description: ""
      label: "RCON_PASSWORD"
      type: "string"
      required: true
      default: "TOCHANGE"
    - variable: SERVER_NAME
      description: ""
      label: "SERVER_NAME"
      type: "string"
      required: true
      default: "LadyStarPT World"
    - variable: DIFFICULTY
      description: "Valid values are: peaceful, easy, normal, and hard, and an error message will be output in the logs if it's not one of these values."
      label: "DIFFICULTY"
      type: "string"
      required: true
      default: "peaceful"
    - variable: OPS
      description: ""
      label: "OPS"
      type: "string"
      required: true
      default: ""

minecraft:
  scale: 1
  start_on_create: true