.catalog:
  name: "nginx-proxy-manager"
  version: 1.0.0
  description: "nginx-proxy-manager"
  uuid: nginx-proxy-manager-1
  questions:
    #VOLUMES
    - variable: configFile
      description: ""
      label: "Path for config file"
      type: "string"
      required: true
      default: "/host/dockers/nginx-proxy-manager/config.json"

    - variable: volumeApp
      description: ""
      label: "Path for app directory"
      type: "string"
      required: true
      default: "/host/dockers/nginx-proxy-manager/app"

    - variable: volumeData
      description: ""
      label: "Path for data directory"
      type: "string"
      required: true
      default: "/host/dockers/nginx-proxy-manager/data"
    
    - variable: volumeLetsencrypt
      description: ""
      label: "Path for letsencrypt directory"
      type: "string"
      required: true
      default: "/host/dockers/nginx-proxy-manager/letsencrypt"

nginx-proxy-manager:
  scale: 1
  start_on_create: true