version: '2'
services:
  database:
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${db_database_name}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_user_password}
      MYSQL_ROOT_PASSWORD: ${db_root_password}
    ports:
      - ${db_port}:3306
    volumes:
      - ${volumeDB}:/var/lib/mysql

  wordpress:
    depends_on:
        - database
    image: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: database:${db_port}
      WORDPRESS_DB_USER: ${db_user}
      WORDPRESS_DB_PASSWORD: ${db_user_password}
      WORDPRESS_DB_NAME: ${db_database_name}
    ports:
      - ${public_port}:80
    volumes:
      - ${volumeHtml}:/var/www/html

#  wordpress-lb:
#    image: rancher/lb-service-haproxy:v0.7.15
#    ports:
#      - ${public_port}:${public_port}