version: '2'
services:
  nginx-cert-generator:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${vCertGeneratorConfd}:/etc/nginx/conf.d:rw
      - ${vCertGeneratorHtml}:/usr/share/nginx/html:rw
    labels:
      io.rancher.container.start_once: "true"

  certbot-staging:
    image: certbot/certbot
    volumes:
      - ${vLetsencryptStagingEtc}:/etc/letsencrypt:rw
      - ${vLetsencryptStagingLib}:/var/lib/letsencrypt:rw
      - ${vCertGeneratorHtml}:/data/letsencrypt:rw
      - ${vLetsencryptStaginglog}:/var/log/letsencrypt:rw
    stdin_open: true
    tty: true
    command: "certonly --webroot --register-unsafely-without-email --agree-tos --webroot-path=/data/letsencrypt --staging -d ${host} -d ${wwwHost}"
    links:
      - nginx-cert-generator
    labels:
      io.rancher.container.start_once: "true"

  certbot-staging-validation:
    image: certbot/certbot
    volumes:
      - ${vLetsencryptStagingEtc}:/etc/letsencrypt:rw
      - ${vLetsencryptStagingLib}:/var/lib/letsencrypt:rw
      - ${vCertGeneratorHtml}:/data/letsencrypt:rw
      - ${vLetsencryptStaginglog}:/var/log/letsencrypt:rw
    stdin_open: true
    tty: true
    links:
      - certbot-staging
    command: "--staging certificates"
    labels:
      io.rancher.container.start_once: "true"

#  nginx:
#    image: nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ${vConfd}:/etc/nginx/conf.d:rw
#      - ${vHtml}:/usr/share/nginx/html:rw
#      - ${vCerts}:/etc/ssl/certs:rw
#      - ${vLetsencryptProdData}:/etc/letsencrypt:rw
    
