version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ${vConfd}:/etc/nginx/conf.d:rw
      - ${vHtml}:/usr/share/nginx/html:rw
      - ${vCerts}:/etc/nginx/certs:rw
    labels:
      rap.host: duartebrito.com=>https:9443
      rap.le_host: duartebrito.com
      rap.le_email: sytertzp@gmail.com
      rap.le_bypass: true
    network_mode: default