.catalog:
  name: "nginx"
  version: "v1"
  description: "nginx"
  uuid: nginx-1
  questions:
    #VOLUMES
    - variable: volumeHtml
      description: ""
      label: "Path for Html"
      type: "string"
      required: true
      default: "/host/dockers/NginxProxy/html"

    - variable: volumeConfd
      description: ""
      label: "Path for conf.d"
      type: "string"
      required: true
      default: "/host/dockers/NginxProxy/conf.d"
    
    - variable: volumeVhostd
      description: ""
      label: "Path for vhost.d"
      type: "string"
      required: true
      default: "/host/dockers/NginxProxy/vhost.d"

    - variable: volumeCerts
      description: ""
      label: "Path for certs"
      type: "string"
      required: true
      default: "/host/dockers/NginxProxy/certs"

    - variable: nginxTemplate
      description: ""
      label: "Path for Nginx Template"
      type: "string"
      required: true
      default: "/host/dockers/NginxProxy/nginx.tmpl"

nginx:
  scale: 1
  start_on_create: true
nginx-gen:
  scale: 1
  start_on_create: true
nginx-letsencrypt:
  scale: 1
  start_on_create: true