version: '2'
services:
  rancher-active-proxy:
    image: adi90x/rancher-active-proxy
    environment:
      DEFAULT_HOST: ${DEFAULT_HOST}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      CRON: ${CRON}
      DEBUG: ${DEBUG}
      DEFAULT_PORT: ${DEFAULT_PORT}
    stdin_open: true
    volumes:
      - ${PATH}/htpasswd:/etc/nginx/htpasswd
      - ${PATH}/vhost.d:/etc/nginx/vhost.d
      - ${PATH}/letsencrypt:/etc/letsencrypt
      - ${PATH}/conf.d:/etc/nginx/conf.d
      - ${PATH}/certs:/etc/nginx/certs
      - ${PATH}/log:/var/log/nginx
    tty: true
    ports:
      - ${DEFAULT_PORT}:80/tcp
      - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always