version: '2'
catalog:
  name: "nginx-proxy-test"
  version: 0.0.1
  description: "nginx-proxy-test"

services:
  nginx-proxy:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true