version: '2'
services:
  ark-server:
    image: syter/ark
    restart: unless-stopped
    ports:
      - "7777:7777"
      - "7777:7777/udp"
      - "${SERVERPORT}:7778"
      - "${SERVERPORT}:7778/udp"
      - "${STEAMPORT}:27015"
      - "${STEAMPORT}:27015/udp"
      - "27021:27021"
      - "27021:27021/udp"
      - "32330:32330"
    environment:
      SESSIONNAME: ${SESSIONNAME}
      SERVERMAP: ${SERVERMAP}
      SERVERPASSWORD: ${SERVERPASSWORD}
      ADMINPASSWORD: ${ADMINPASSWORD}
      SERVERPORT: ${SERVERPORT}
      STEAMPORT: ${STEAMPORT}
      BACKUPONSTART: ${BACKUPONSTART}
      UPDATEPONSTART: ${UPDATEPONSTART}
      BACKUPONSTOP: ${BACKUPONSTOP}
      WARNONSTOP: ${WARNONSTOP}
      TZ: ${TZ}
      AUTOUPDATE: 120
      AUTOBACKUP: 60
      WARNMINUTE: 30
    volumes:
    - ${volumeArk}:/ark:rw
    network_mode: host
