version: '2'
services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ${volumeHtml}:/var/www/html:rw
      - ${volumeCustomConf}:/etc/nginx/conf.d/custom.conf:rw
      - ${volumeDefaultConf}:/etc/nginx/conf.d/default.conf:rw
    ports:
      - "80:80"